#!/bin/bash

# This script connects to a website using Google Chrome.
#
# Run in Terminal with the following commands
# sh open_multiple <address> <numberOfConnections> <timeIntervall>
#   
# Example: 
# sh open_multiple http://www.dn.se 3 0.5


# Hard coded variables:
RUN="/usr/bin/open -a"
APP="/Applications/Google Chrome.app/"


#The url is given by the first argument
if [ -z "$1" ]; then
    URL="http://www.google.se"
else
    URL=$1
fi

#Number of calls to do
N_CALLS=1 # default
if [ $2 -gt $N_CALLS ]
then
	N_CALLS=$2
fi

#Time intervall
TIME_INTERVALL=0.0 #seconds
if [ $3 -gt 0 ]
then
	TIME_INTERVALL=$3
fi





#Print all variables for debugging
#echo "url =" $URL
#echo "number of calls =" $N_CALLS
#echo "caller =" $RUN
#echo "application =" $APP
#echo "calls to be done:" $CALL_COMMAND

COUNTER=0
while [ $COUNTER -lt $N_CALLS ]
do
	COUNTER=$((COUNTER + 1))
	echo $COUNTER
	$RUN "$APP" "$URL"
	sleep $TIME_INTERVALL
done
